### ISSUE TITLE
Support feature structures referencing other feature structures

### ISSUE THREAD

**Issue by GregSilverman** [dkpro/dkpro-cassis#45] opened 2019-02-08 21:06 UTC
**Describe the bug**

We have an annotation type that has a feature structure that is referenced via a feature/attribute, but the feature structure is not being displayed in the loaded CAS object.

**To Reproduce**

I am able to query the annotation type just fine, but the feature structure does not show up when I do a `load_cas_from_xmi`

Annotation type in question is: `textsem:MedicationMention` (or ProcedureMention, etc) and is linked to `refsem:UmlsConcept` via `ontologyConceptArr`.

I've tried: 

```
print([x for x in cas.select('org.apache.ctakes.typesystem.type.refsem.UmlsConcept')])
print([x for x in cas.select_all()])
```

and 

```
view = cas.get_view('_InitialView')
print([x for x in view.select_all()])
```

all to no avail.

**Expected behavior**

Expect to see `refsem:UmlsConcept` in the displayed CAS.

**Please complete the following information:**
 - Version: [0.2.0.dev0]
 - OS: OS X

**Additional context**

Attached are XMI and Typesystem example:
[ctakes_out.zip](https://github.com/dkpro/dkpro-cassis/files/2846841/ctakes_out.zip)

**Comment by GregSilverman** [comment] 2019-02-08 21:49
NB: the type is getting loaded when I do 
```
with open(dir_test + 'TypeSystem.xml', 'rb') as f:
    typesystem = load_typesystem(f)
    for t in typesystem.get_types():
        print(t)
        print('\n') :
```

`Type(name='org.apache.ctakes.typesystem.type.refsem.UmlsConcept', supertypeName='org.apache.ctakes.typesystem.type.refsem.OntologyConcept', description='Concepts in the Unified Medical Language System (UMLS) Metathesaurus have a concept unique identifier (CUI) and a type unique identifier (TUI, i.e., semantic type) which are curated, normalized codes. For example, "pain" would have a cui=C0030193 and tui=T184.\nEquivalent to cTAKES: edu.mayo.bmi.uima.core.type.UmlsConcept', _children=set(), _features={'cui': Feature(name='cui', rangeTypeName='uima.cas.String', description=None, elementType=None, multipleReferencesAllowed=None), 'tui': Feature(name='tui', rangeTypeName='uima.cas.String', description=None, elementType=None, multipleReferencesAllowed=None), 'preferredText': Feature(name='preferredText', rangeTypeName='uima.cas.String', description='preferredText is the preferred term. normally his is\t \n           \tthe UMLS preferred name.', elementType=None, multipleReferencesAllowed=None)}, _inherited_features={'codingScheme': Feature(name='codingScheme', rangeTypeName='uima.cas.String', description=None, elementType=None, multipleReferencesAllowed=None), 'code': Feature(name='code', rangeTypeName='uima.cas.String', description=None, elementType=None, multipleReferencesAllowed=None), 'oid': Feature(name='oid', rangeTypeName='uima.cas.String', description=None, elementType=None, multipleReferencesAllowed=None), 'oui': Feature(name='oui', rangeTypeName='uima.cas.String', description='holds the rxnorm unique identifier for a given drug mention.\n\t\t\t\t\t\t\tTODO: change this attribute because of name clash (UMLS/SNOMED)', elementType=None, multipleReferencesAllowed=None), 'score': Feature(name='score', rangeTypeName='uima.cas.Double', description='Word Sense disambiguation: if this named entity is assigned multiple ontologyConcepts, the score represents how similar this sense is to surrounding senses (higher scores = more likely to be the correct sense)', elementType=None, multipleReferencesAllowed=None), 'disambiguated': Feature(name='disambiguated', rangeTypeName='uima.cas.Boolean', description='Word Sense disambiguation: if this named entity is assigned multiple ontologyConcepts, then the OntologyConcept with disambiguated=true is the most likely sense', elementType=None, multipleReferencesAllowed=None)})`

**Comment by jcklie** [comment] 2019-02-08 22:50
Thank you for the report! I will look into it as soon I have time. I sadly am on a conference next week, so I do not know when that will be.

**Comment by jcklie** [comment] 2019-02-08 23:20
I think that one would implement a function to check whether a feature is an array type. This can then be used in the xmi reader when deserializing: If the range type of your feature is of array type, split the attribute text and save the ids somewhere. At the end, you need to look up the annotations with the ids and fill them in.

**Comment by GregSilverman** [comment] 2019-02-11 23:54
@jcklie, I will take a look at this as per your suggestion. Any ideas as how to save the ids listed in the array for lookup, would be most welcome.

**Comment by GregSilverman** [comment] 2019-02-13 02:52
Got a working solution for this. I need to do some more testing and to also expand this beyond use of `rangeTypeName` of `Array` type, since there are other features that have this foreign-key like behavior where the xmi:Id is not in the sofa lookup list.

**Comment by jcklie** [comment] 2019-02-20 09:46
@GregSilverman I added support for references to master. The issue that you do not get `org.apache.ctakes.typesystem.type.refsem.UmlsConcept` get back is a follow up problem which I will tackle next with #15 .

**Comment by jcklie** [comment] 2019-02-20 10:39
I checked, I already perform select like it should be. The issue is that the `UmlsConcept` is not in a view, therefore, you need to select the feature structures that are referencing it.

```
from cassis import *

with open('TypeSystem.xml', 'rb') as f:
    typesystem = load_typesystem(f)

with open('737-v1.txt.xmi', 'rb') as f:
    cas = load_cas_from_xmi(f, typesystem=typesystem)

for e in cas.select("org.apache.ctakes.typesystem.type.textsem.MedicationMention"):
    print(e.ontologyConceptArr)
```

**Comment by GregSilverman** [comment] 2019-02-20 15:24
@jcklie , I can make a push request with my code that fixed this issue.

**Comment by jcklie** [comment] 2019-02-20 15:26
I also already fixed it I think.

**Comment by GregSilverman** [comment] 2019-02-20 15:30
I'll make the PR anyway, just for your amusement.

**Comment by jcklie** [comment] 2019-02-20 15:43
@GregSilverman Thank you! Can you try whether the master works for you now? If yes, then I would prepare a release, if not, then I would continue fixing it.

**Comment by GregSilverman** [comment] 2019-02-20 15:53
Yes, I should be able to do so later today.

**Comment by GregSilverman** [comment] 2019-02-21 03:31
Got a little side tracked. I should be able to get to this in the next couple days. It is a priority, but is in a long list of items slowly getting checked off...

**Comment by GregSilverman** [comment] 2019-02-23 20:17
More side tracked. It might be a while before I get to testing this, since I am deep in an experiment. It has been shifted down in priority, since everything I need is functional as of this moment.

**Comment by GregSilverman** [comment] 2019-04-17 19:55
Hi sorry about the delay. I should be able to get to this very soon.

**Comment by GregSilverman** [comment] 2019-05-06 22:56
Am on it now. Time away from it has made everything seem VERY unfamiliar.

**Comment by GregSilverman** [comment] 2019-07-04 18:58
Hi, finally back to use of this for a project. 

I wanted to check about issue #48. Do I need to still add an `id` attribute to the annotation type that gets linked to the annotation with the linking `id` in it? We just ran across this issue in an inception schema we implemented. 

So, here is an annotation type with a linked id in it:

`webanno_custom_StressfulEventStressLink(xmiID=397, role='Causality', target='4466', type='webanno.custom.StressfulEventStressLink')`

and here is the annotation type to which it maps via the `target` attribute:

`webanno_custom_StressMention(xmiID=385, begin=435, end=462, sofa=1, type='webanno.custom.StressMention')`

It looks also like the attribute `Stress` maps back to the type `StressfulEventStressLink`.

I can use my own code modifications if need be, but if your changes fixed this issure, that would be great.

Also, for this issue #45, is the version in the `master` branch the one I need to test?

Thanks a bunch! This tool is saving us former Java programmers turned in Python-geeks a ton of effort.

**Comment by jcklie** [comment] 2019-07-05 07:41
The ids still are not preserved over a serializing/deserializing cycle but they are still pointing to the same annotations. With the newest chagnes, `link.target` would be the actual annotation, not an ID. I do not understand your example, as there are no pairs of ids that are the same, are they? You need to check master, yes.

**Comment by GregSilverman** [comment] 2019-07-05 14:17
Got it. Thanks. Sorry about eh nonsensical example. I just updated the linking ids, accordingly..

**Comment by GregSilverman** [comment] 2019-07-09 14:55
@jcklie In the original example, `link.target` and the `xmiid` it was pointing to were not preserved. That is what I wanted to show. I updated the example to what I wanted to achieve.

This is my desired:

`webanno_custom_StressfulEventStressLink(xmiID=397, role='Causality', target='385', type='webanno.custom.StressfulEventStressLink')`

and here is the `to` part of the relationship annotation type mapped via the `target` attribute:

`webanno_custom_StressMention(xmiID=385, begin=435, end=462, sofa=1, type='webanno.custom.StressMention')`

but this is what I get

`webanno_custom_StressfulEventStressLink(xmiID=397, role='Causality', target='385', type='webanno.custom.StressfulEventStressLink')`

and here is the `to` part of the relationship annotation type mapped via the `target` attribute:

`webanno_custom_StressMention(xmiID=38, begin=435, end=462, sofa=1, type='webanno.custom.StressMention')`

since the xmid is not preserved. The use of an intermediary `id` to store the original `xmiid` was a kludgey solution, and it woorked.

**Comment by GregSilverman** [comment] 2019-07-09 14:58
Again, see #48 for details. Thanks!

**Comment by GregSilverman** [comment] 2019-07-09 16:32
Mea culpa. I was in the wrong virtualenv. I will try doing the linkage from the code from master.

**Comment by GregSilverman** [comment] 2019-07-17 13:35
Hi, I just wanted to confirm that #48 is fixed. We just tested it on a set of documents annotated in inception. I should be able to test the fixes outlined for this issue in the next couple weeks.

**Comment by jcklie** [comment] 2019-07-21 11:52
For me this works in master and 0.2.0-rc1. I will close this now. Please reopen this issue if this error still persists.

**Closed by jcklie** 2019-07-21 11:52 UTC
Labels: Module: CAS, 🆕Enhancement
