### ISSUE TITLE
AttributeError while serializing CAS with string array inheritance

### ISSUE THREAD

**Issue by reneverheij** [dkpro/dkpro-cassis#100] opened 2019-12-01 14:06 UTC
Call to cas.to_xmi() fails with AttributeError:
```
Traceback (most recent call last):
  File "c:\Users\x\git\uima_python\python\uima_rest\test\test_ner_service_wex.py", line 22, in test_process
    xmi_out = service.process(xmi_in, tsd)
  File "c:\Users\x\git\uima_python\python\uima_rest\ner_service\NerService.py", line 37, in process
    xmi_string = cas.to_xmi()
  File "C:\Users\x\Anaconda3\envs\uima_rest\lib\site-packages\cassis\cas.py", line 390, in to_xmi
    serializer.serialize(sink, self, pretty_print=pretty_print)
  File "C:\Users\x\Anaconda3\envs\uima_rest\lib\site-packages\cassis\xmi.py", line 257, in serialize
    for fs in sorted(self._find_all_fs(cas), key=lambda a: a.xmiID):
  File "C:\Users\x\Anaconda3\envs\uima_rest\lib\site-packages\cassis\xmi.py", line 297, in _find_all_fs
    if referenced_fs.xmiID not in all_fs:
AttributeError: 'str' object has no attribute 'xmiID'

```
**To Reproduce**
Create a CAS based on the attached XMI document and type system descriptor.

**Please complete the following information:**
- Version: 0.2,5
- OS: Windows 10
- Python: 3.8.0

[testdata.zip](https://github.com/dkpro/dkpro-cassis/files/3908274/testdata.zip)

**Comment by jcklie** [comment] 2019-12-01 15:54
The problem is that I did not check things extending string arrays when serializing. A fix is underway.

**Comment by jcklie** [comment] 2019-12-01 16:21
It should be fixed in master, I might do a release next week.

**Comment by reneverheij** [comment] 2019-12-02 20:38
After pulling the master branch, the error has disappeared.

**Comment by reneverheij** [comment] 2019-12-08 07:43
Any chance of a release today? I’d really appreciate it.

**Comment by jcklie** [comment] 2019-12-08 14:45
I released it.

**Closed by jcklie** 2019-12-08 14:45 UTC
Labels: Module: XMI, 🐛Bug
