### ISSUE TITLE
uima.tcas.DocumentAnnotation not predefined when deserializing from JSON

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#278] opened 2023-02-09 10:40 UTC
**Describe the bug**

uima.tcas.DocumentAnnotation is not predefined and not added by default to the TypeSystem

**Comment by jcklie** [comment] 2023-02-09 10:47
with p.open("rb") as f:
        ts = TypeSystem(add_document_annotation_type=True)

        cassis.load_cas_from_json(f, typesystem=ts)

is sometimes required

**Comment by jcklie** [comment] 2023-02-09 10:48
The issue occurs when a type extends from `uima.tcas.DocumentAnnotation` but does not define it, e.g. 

"de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData" : {
      "%NAME" : "de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData",
      "%SUPER_TYPE" : "uima.tcas.DocumentAnnotation",
      "documentTitle" : {
        "%NAME" : "documentTitle",
        "%RANGE" : "uima.cas.String"
      },

**Comment by reckart** [comment] 2024-02-04 09:44
Seems to be a duplicate of #280

**Closed** 2024-02-04 09:45 UTC
Labels: 🐛Bug, Module: Json
